after-login-command = []

after-startup-command = [
  'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -150'
alt-shift-equal = 'resize smart +150'

alt-b = 'workspace B' # Browser
alt-d = 'workspace D' # Database
alt-p = 'workspace P' # Programming
alt-c = 'workspace C' # Slack / Communication
alt-v = 'workspace V' # Vanity-stuff on second monitor
alt-m = 'workspace M' # Music applications

alt-shift-b = 'move-node-to-workspace B'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-c = 'move-node-to-workspace C'
alt-shift-v = 'move-node-to-workspace V'
alt-shift-m = 'move-node-to-workspace M'

[workspace-to-monitor-force-assignment]
B = 'main'
P = 'main'
D = 'main'
M = 'main'
C = ['^built-in retina display$', 'secondary']
V = ['^built-in retina display$', 'secondary']

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']


alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace C"

[[on-window-detected]]
if.app-id = 'com.jetbrains.PhpStorm'
run = "move-node-to-workspace P"

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = "move-node-to-workspace P"

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = "move-node-to-workspace P"

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace V"

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus-setapp'
run = "move-node-to-workspace D"

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = "move-node-to-workspace P"
