[location]
# Location coordinates (overridden if auto = true)
latitude = 52.2753103
longitude = 8.0448273
auto = false

[units]
# Temperature unit: "celsius" or "fahrenheit"
temperature = "celsius"

# Wind speed unit: "kmh", "ms", "mph", or "kn"
wind_speed = "kmh"

# Precipitation unit: "mm" or "inch"
precipitation = "mm"
